parserOptions:
    ecmaVersion: 6
    sourceType: module
extends: "eslint:recommended"
env:
    node: true
    jasmine: true
    atomtest: true
    es6: true
globals:
    atom: true
rules:
    no-console: [0]
    semi: [2]
